---
- name: Agent-based Installer
  hosts: localhost
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  tasks:
    - name: Create cluster install dir
      ansible.builtin.file:
        path: "{{ openshift_cluster_install_dir }}"
        mode: '0755'
        state: directory

    - name: Generate agent-config.yaml
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ openshift_cluster_install_dir }}/{{ item }}"
        mode: '0644'
#      vars: 
#        rendezvousIP: "{{ hostvars['master-0'].IP }}"
      with_items:
       - install-config.yaml
       - agent-config.yaml
      ## FIX needed to get vars into template

    - name: Create copys of agent-config and install configuration
      ansible.builtin.copy:
        src: "{{ openshift_cluster_install_dir }}/{{ item }}"
        dest: "{{ openshift_cluster_install_dir }}/{{ item }}-copy"
        remote_src: yes
      with_items:
       - install-config.yaml
       - agent-config.yaml

    - name: Generate ISO
      register: generate_iso
      changed_when:
        - generate_iso.rc == 0
      ansible.builtin.command: |
        {{ openshift_client_bin }}/openshift-install \
        agent create image \
        --log-level debug \
        --dir {{ openshift_cluster_install_dir }}
