---
- name: generete oc-mirror imagesetconfig
  ansible.builtin.template:
    src: imagesetconfig.yml.j2
    dest: "{{ openshift_download_dir }}/imagesetconfig.yml"

- name: Fix formating of generated imagesetconfig
  ansible.builtin.replace:
    path: "{{ openshift_download_dir }}/imagesetconfig.yml"
    regexp: "{{ item }}"
    replace: ""
  with_items: 
    - '^\s*$'
    - '[ \t]+$'

- name: remove empty lines with sed
  ansible.builtin.shell: sed -i '/^$/d' {{ openshift_download_dir }}/imagesetconfig.yml

- name: fix permisison on oc-mirror to make executable
  ansible.builtin.file:
    path: "{{ openshift_client_bin }}/oc-mirror"
    mode: '0755'

- name: Run oc-mirror to generate image tar
  ansible.builtin.command: "{{ openshift_client_bin }}/oc-mirror --config imagesetconfig.yml \ 
    file://{{ openshift_download_dir }}/"
  args:
    chdir: "{{ openshift_download_dir }}"
  when: pull_mirror | bool
