---
- name: Configure Firewall for Red Hat Quay
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Set Firewall
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.posix.firewalld:
        state: enabled
        port: "{{ item }}"
        immediate: true
        permanent: true
      loop:
        - "80/tcp"
        - "443/tcp"
        - "5432/tcp"
        - "6379/tcp"
