---
- name: Create operator config directory
  ansible.builtin.file:
    src: "{{ openshift_cluster_config_dir }}/operators"
    mode: '0755'
    directory: yes

- name: Generate operator install configs
  ansible.builtin.template:
    src: base.yml.j2
    dest: "{{ openshift_cluster_config_dir }}/operators/{{ item.name }}.yml"
  with_items:
    - "{{ install_operators }}"

- name: Apply generated operator configs
  kubernetes.core.k8s:
    src: "{{ openshift_cluster_config_dir }}/operators/{{ item.name }}.yml"
  with_items:
    - "{{ install_operators }}"

