---
- name: Install client utilities
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Install oc
      ansible.builtin.unarchive:
        src: "{{ openshift_download_dir }}/openshift-client-linux-{{ openshift_version }}.tar.gz"
        remote_src: true
        exclude:
          - README.md
        dest: "{{ openshift_client_bin }}"

    - name: Install oc-mirror
      ansible.builtin.unarchive:
        src: "{{ openshift_download_dir }}/oc-mirror.tar.gz"
        remote_src: true
        exclude:
          - README.md
        dest: "{{ openshift_client_bin }}"

    - name: Fix permissions on oc-mirror
      ansible.builtin.file:
        path: "{{ openshift_client_bin }}/oc-mirror"
        owner: root
        group: root
        mode: '0755'
      failed_when: false

    - name: Install openshift-installer
      ansible.builtin.unarchive:
        src: "{{ openshift_download_dir }}/openshift-install-linux-{{ openshift_version }}.tar.gz"
        remote_src: true
        exclude:
          - README.md
        dest: "{{ openshift_client_bin }}"

    - name: Install tridentctl
      ansible.builtin.unarchive:
        src: "{{ openshift_download_dir }}/trident-installer-{{ trident_version }}.tar.gz"
        remote_src: true
        include:
          - trident-installer/tridentctl
        dest: "{{ openshift_client_bin }}"

    - name: Move tridentctl to proper location
      ansible.builtin.copy:
        remote_src: true
        src: "{{ openshift_client_bin }}/trident-installer/tridentctl"
        dest: "{{ openshift_client_bin }}/tridentctl"
        mode: '0755'

    - name: Remove trident-installer/tridentctl
      ansible.builtin.file:
        path: "{{ openshift_client_bin }}/trident-installer/tridentctl"
        state: absent
