---
- name: Download client utilities
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Download oc
      ansible.builtin.get_url:
        url: "{{ openshift_download_base_url }}/openshift-client-{{ openshift_bastion_platform }}-{{ openshift_version }}.tar.gz"
        dest: "{{ openshift_download_dir }}"
        mode: '0644'
      register: download_oc

    - name: Download oc-mirror
      ansible.builtin.get_url:
        url: "{{ openshift_download_base_url }}/oc-mirror.tar.gz"
        dest: "{{ openshift_download_dir }}"
        mode: '0644'
      register: download_mirror

    - name: Download openshift-installer
      ansible.builtin.get_url:
        url: "{{ openshift_download_base_url }}/openshift-install-{{ openshift_bastion_platform }}-{{ openshift_version }}.tar.gz"
        dest: "{{ openshift_download_dir }}"
        mode: '0644'
      register: download_installer

    - name: Download trident
      ansible.builtin.get_url:
        url: https://github.com/NetApp/trident/releases/download/v{{ trident_version }}/trident-installer-{{ trident_version }}.tar.gz
        dest: "{{ openshift_download_dir }}"
        owner: root
        mode: '0644'
