---
- name: Configure node networks
  hosts: localhost
  become: true
  gather_facts: false
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  tasks:
    - name: Configure bonded interfaces
      kubernetes.core.k8s:
        state: present
        template: network/node/bond.yaml.j2

    - name: Configure management network
      kubernetes.core.k8s: # eno2
        state: present
        template: network/node/mgmt.yaml.j2

    - name: Configure netapp storage network
      kubernetes.core.k8s:
        state: present
        template: network/node/netapp.yaml.j2

    - name: Configure virtual machine network
      kubernetes.core.k8s:
        state: present
        template: network/node/vm.yaml.j2
