---
- name: Configure node networks
  hosts: localhost
  become: true
  gather_facts: false
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  tasks:
    - name: Configure bond0
      kubernetes.core.k8s:
        definition:
          spec:
            desiredState:
              interfaces:
                - name: bond0
                  description: Bonding root interface for NetApp
                  type: bond
                  state: up
                  ipv4:
                    dhcp: true
                    enabled: true
                  link-aggregation:
                    mode: active-backup
                    port:
                      - ens2f0
                      - ens2f1
                      - ens3f0
                      - ens3f1

    - name: Configure management network
      kubernetes.core.k8s: # eno2

    - name: Configure netapp
      kubernetes.core.k8s:
