---
- name: Create Red Hat Quay Directories
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Create Quay Configuration Directory
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.builtin.file:
        state: directory
        path: "{{ quay_config_path }}"
        mode: '0755'
        owner: 1001
        group: 0

    - name: Set File ACLs on Quay Configuration Directory
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.posix.acl:
        state: present
        path: "{{ quay_config_path }}"
        etype: user
        entity: 1001
        permissions: -wx

    - name: Create Quay Storage Directory
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.builtin.file:
        state: directory
        path: "{{ quay_storage_path }}"
        mode: '0755'
        owner: 1001
        group: 0

    - name: Set File ACLs on Quay Storage Directory
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.posix.acl:
        state: present
        path: "{{ quay_storage_path }}"
        etype: user
        entity: 1001
        permissions: -wx
