---
- name: Configure Redis for Red Hat Quay
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Start Redis Server
      containers.podman.podman_container:
        state: started
        name: quay-redis
        image: registry.redhat.io/rhel8/redis-6:1-110
        hostname: "{{ quay_redis_hostname | default(omit) }}"
        network: "{{ quay_container_network | default(omit) }}"
        ip: "{{ quay_redis_ip | default('0.0.0.0') }}"
        restart_policy: "always"
        env:
          REDIS_PASSWORD: "{{ quay_redis_password }}"
        # publish:
        #   - "6379:6379"
