---
- name: Configure PostgreSQL for Red Hat Quay
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Create PostgreSQL Storage
      # when:
        # - ansible_os_family == 'RedHat'
      ansible.builtin.file:
        state: directory
        path: "{{ quay_postgresql_path }}"
        mode: '0755'

    - name: Set File ACLs
      # when:
        # - ansible_os_family == 'RedHat'
      ansible.posix.acl:
        state: present
        path: "{{ quay_postgresql_path }}"
        etype: user
        entity: 26
        permissions: -wx

    - name: Start PostgreSQL Server
      containers.podman.podman_container:
        state: started
        name: quay-postgresql
        image: registry.redhat.io/rhel8/postgresql-13:1-109
        hostname: "{{ quay_postgresql_hostname | default(omit) }}"
        network: "{{ quay_container_network | default(omit) }}"
        ip: "{{ quay_postgresql_ip | default('0.0.0.0') }}"
        restart_policy: "always"
        env:
          POSTGRESQL_USER: "{{ quay_postgresql_username }}"
          POSTGRESQL_PASSWORD: "{{ quay_postgresql_password }}"
          POSTGRESQL_DATABASE: "{{ quay_postgresql_database }}"
          POSTGRESQL_ADMIN_PASSWORD: "{{ quay_postgresql_admin_password }}"
        # publish:
        #   - "5432:5432"
        volume:
          - "{{ quay_postgresql_path }}:/var/lib/pgsql/data:Z"
