---
- name: Configure Firewall for Red Hat Clair
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Set Firewall
      ansible.posix.firewalld:
        state: enabled
        port: "{{ item }}"
        immediate: true
        permanent: true
      loop:
        - "8081/tcp"
        - "8088/tcp"
        - "5433/tcp"
