---
- name: Configure PostgreSQL for Red Hat Clair
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Create PostgreSQL Storage
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.builtin.file:
        state: directory
        path: "{{ clair_postgresql_path }}"
        mode: '0755'

    - name: Set File ACLs
      # when:
      #   - ansible_distribution == 'RedHat'
      ansible.posix.acl:
        state: present
        path: "{{ clair_postgresql_path }}"
        etype: user
        entity: 26
        permissions: -wx

    - name: Start Clair Postresql Server
      containers.podman.podman_container:
        state: started
        name: clair-postgresql
        image: registry.redhat.io/rhel8/postgresql-13:1-109
        hostname: "{{ clair_postgresql_hostname | default(omit) }}"
        network: "{{ quay_container_network | default(omit) }}"
        ip: "{{ clair_postgresql_ip | default('0.0.0.0') }}"
        env:
          POSTGRESQL_USER: "{{ clair_postgresql_username }}"
          POSTGRESQL_PASSWORD: "{{ clair_postgresql_password }}"
          POSTGRESQL_DATABASE: "{{ clair_postgresql_database }}"
          POSTGRESQL_ADMIN_PASSWORD: "{{ clair_postgresql_admin_password }}"
        publish:
          - "5433:5432"
        volume:
          - "{{ clair_postgresql_path }}:/var/lib/pgsql/data:Z"
