---
- name: Configure Red Hat Clair
  hosts: quay-host
  gather_facts: false
  become: true

  tasks:
    - name: Write Clair Config.yaml
      ansible.builtin.template:
        src: clair.yaml
        dest: "{{ clair_config_path }}/config.yaml"
        mode: '0644'
