---
trident_version: "23.07.0"
trident_namespace: "trident-system"
trident_registry: "{{ internal_registry }}/sig-storage"
trident_image: "{{ internal_registry }}/netapp/trident:{{ trident_version }}"
trident_autosupport: "{{ internal_registry }}/netapp/trident-autosupport:{{ trident_version[0:5] }}"
trident_operator: "{{ internal_registry }}/netapp/trident-operator:{{ trident_version }}"

trident_controller_annotations:
  k8s.v1.cni.cncf.io/networks: management

sig_storage_images: []
