---
- name: Configure Control Plane to be Schedulable
  hosts: localhost
  become: true
  gather_facts: false
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeConfig: $HOME/.kube/config
  tasks:
    - name: Configure Scheduler
      kubernetes.core.k8s:
        state: patched
        api_version: config.openshift.io/v1
        kind: Scheduler
        name: cluster
        definition:
          spec:
            mastersSchedulable: true
