http_listen_addr: :8081
introspection_addr: :8088
log_level: debug
indexer:
  connstring: host={{ clair_postgresql_hostname }} port={{ clair_postgresql_port }} dbname={{ clair_postgresql_database }} user={{ clair_postgresql_username }} password={{ clair_postgresql_password }} sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host={{ clair_postgresql_hostname }} port={{ clair_postgresql_port }} dbname={{ clair_postgresql_database }} user={{ clair_postgresql_username }} password={{ clair_postgresql_password }} sslmode=disable
  max_conn_pool: 100
  migrations: true
  indexer_addr: clair-indexer
notifier:
  connstring: host={{ clair_postgresql_hostname }} port={{ clair_postgresql_port }} dbname={{ clair_postgresql_database }} user={{ clair_postgresql_username }} password={{ clair_postgresql_password }} sslmode=disable
  delivery_interval: 1m
  poll_interval: 5m
  migrations: true
auth:
  psk:
    key: "{{ clair_psk }}"
    iss: ["quay"]
# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent:
      endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"