---
- name: Download client utilities
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create cluster bin dir
      ansible.builtin.file:
        path: "{{ openshift_download_dir }}"
        mode: '0755'
        state: directory

    - name: Download oc tools
      ansible.builtin.get_url:
        url: "{{ openshift_download_base_url }}/ocp/{{ openshift_release }}/{{ item }}"
        dest: "{{ openshift_download_dir }}"
        mode: '0644'
      with_items:
        - openshift-client-linux.tar.gz
        - oc-mirror.tar.gz
        - openshift-install-linux.tar.gz
      register: download_tools

    - name: Download trident
      ansible.builtin.get_url:
        url: "https://github.com/NetApp/trident/releases/download/{{ trident_version }}/trident-installer-{{ trident_version  | replace('v', '') }}.tar.gz"
        dest: "{{ openshift_download_dir }}"
        mode: '0644'
      register: download_tridant
