---
- name: Install openshift-installer utilities
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Install openshift-installer
      ansible.builtin.unarchive:
        src: "{{ openshift_download_dir }}/openshift-install-linux-{{ openshift_release }}.tar.gz"
        remote_src: true
        exclude:
          - README.md
        dest: "{{ openshift_client_bin }}"
