---
- name: Provision NetApp
  hosts: netapp
  gather_facts: false

  vars:
    boot_source_mode: "UEFI"

  # module_defaults:
  #   dellemc.openmanage.idrac_virtual_media:
  #   dellemc.openmanage.idrac_boot:

  tasks:
    # - name: Configure Controller A
    #   when:
    #     - inventory_host == netapp_controller_a
    - name: Install NetApp Licenses
    - name: Set NTP
    - name: Set Timezone
    - name: Rename the Root Aggregate
    - name: Create and online a new Data Aggregate
    - name: Create a Vserver
    - name: Setup a VLAN
    - name: Creating a Broadcast Domain
    - name: Subnet Creation
    - name: Create an NFS Lif
    - name: Start NFS
    - name: Create NFS Export Rule
    - name: Add DNS Settings to Vserver
    - name: Create first NFS Volume
    - name: Create an additional NFS Volume
