---
- name: Generate oc-mirror image content
  hosts: localhost
  gather_facts: false
  tasks:
  - name: generete oc-mirror imagesetconfig
    ansible.builtin.template:
      src: imagesetconfig.yml.j2
      dest: "{{ openshift_download_dir }}/imagesetconfig.yml"

  - name: fix formating of generated imagesetconfig
    ansible.builtin.replace:
      path: "{{ openshift_download_dir }}/imagesetconfig.yml"
      regexp: ".*- catalog"
      replace: "  - catalog"

  - name: Run oc-mirror to generete image tar
    ansible.builtin.command: oc-mirror --config imagesetconfig.yml \ 
      file://"{{ openshift_download_dir }}/"
    args:
      chdir: "{{ openshift_download_dir }}"
    when: pull_mirror | bool