---
- name: Configure GitLab
  hosts: quay-host
  gather_facts: false
  become: true

  vars:
    gitlab_path: /home/gitlab

  tasks:
    # - name: Write Config
    #   ansible.builtin.template:
    #     src: quay.yaml
    #     dest: "{{ quay_config_path }}/config.yaml"
    #     mode: '0644'

    - name: Start GitLab
      containers.podman.podman_container:
        state: started
        name: gitlab
        image: docker.io/gitlab/gitlab-ee:16.6.6-ee.0
        hostname: gitlab.developer.hkn.lab
        shm_size: 256m
        publish:
          - "172.16.30.31:22:22"
          - "172.16.30.31:80:80"
          - "172.16.30.31:443:443"
        volume:
          - "{{ gitlab_path }}/config:/etc/gitlab:Z"
          - "{{ gitlab_path }}/logs:/var/log/gitlab:Z"
          - "{{ gitlab_path }}/data:/var/opt/gitlab:Z"
