---
all:
  children:
    cisco:
      children:
        nxos:
          children:
            c3172tq:
              hosts:
                switch:
    netapp:
      children:
        netapp_cluster:
          hosts:
            naCluster:
              ansible_host: 172.16.100.100
        netapp_controllers:
          hosts:
            netapp-ctrl-a:
            netapp-ctrl-b:
    registry:
      hosts:
        quay-host:
    jumpbox:
      hosts:
        bastion:
    openshift:
      hosts:
        localhost:
          ansible_connection: local
        master-0:
        master-1:
        master-2:
        worker-0:
    idrac:
      hosts:
        master-0:
        master-1:
        master-2:
        worker-0:
    quay:
      hosts:
        quay-host:
        localhost:
          ansible_connection: local
