---
all:
  children:
    cisco:
      hosts:
        switch:
    netapp:
      hosts:
        netapp-ctrl-a:
        netapp-ctrl-b:
        netapp-cluster:
    jumpbox:
      hosts:
        bastion:
        quay:
    openshift:
      hosts:
        localhost:
        master-0:
        master-1:
        master-2:
        worker-0:
    idrac:
      hosts:
        master-0:
        master-1:
        master-2:
        worker-0:
