---
- name: Configure pod networks
  hosts: localhost
  become: true
  # module_defaults:
  #   kubernetes.core.k8s:
  #     kubeconfig: $HOME/.kube/config
  tasks:
    - name: Create NetworkAttachmentDefinitions
      kubernetes.core.k8s:
        definition:
          api_version: network.kubernetes.io
          kind: NetworkAttachmentDefinitions
          metadata:
            name:
            namespace:
          spec: {}
