---
- name: Download clients
  ansible.builtin.import_playbook: openshift/tools/download.yml
- name: Install openshift client cli
  ansible.builtin.import_playbook: openshift/tools/clients.yml
- name: Install openshift cli
  ansible.builtin.import_playbook: openshift/tools/installer.yml
- name: Install trident cli
  ansible.builtin.import_playbook: openshift/tools/trident.yml
