---
- name: Configure OLM
  ansible.builtin.import_playbook: openshift/olm.yml
- name: Install NMState Operator
  ansible.builtin.import_playbook: openshift/operator_nmstate.yml
- name: Install node networks
  ansible.builtin.import_playbook: openshift/networks_node.yml
- name: Install pod networks
  ansible.builtin.import_playbook: openshift/networks_pod.yml
- name: Install Trident CSI
  ansible.builtin.import_playbook: openshift/storage_trident.yml
- name: Install Keycloak
  ansible.builtin.import_playbook: openshift/operator_keycloak.yml
